# Generated by Django 5.1.4 on 2024-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=255, verbose_name='Usuario')),
                ('user_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('user_last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('user_password', models.BinaryField(max_length=255, verbose_name='contraseña')),
                ('user_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('user_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('user_enable', models.BooleanField(default=True, verbose_name='Activo')),
                ('user_lock', models.BooleanField(default=False, verbose_name='Bloqueado')),
            ],
        ),
    ]
