# Generated by Django 5.1.4 on 2025-01-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_password',
        ),
    ]
