services:
  db_auth:
    image: postgres
    container_name: db_user_postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: desarrollo
      POSTGRES_PASSWORD: desa1234*.#rollo
    ports:
      - 5433:5432
    volumes:
      - .dbdata_auth:/var/lib/postgresql
    networks:
      - red

volumes:
  .dbdata_auth:
      
networks:
    red:
        external: true