global:
  sendAnonymousUsage: false

entryPoints: 
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"


api:
  insecure: true
  dashboard: true


log: 

  level: INFO  
  format: common  
  
providers: 
  docker:
    endpoint: "unix:///var/run/docker.sock" 
    exposedByDefault: false 
    watch: true 
    network: traefik-net
  
  file:
    filename: /etc/traefik/config.yml
    watch: true

   