services:
  app:
    build: .
    ports:
      - "5173:5173" # Mapea el puerto 5173 del contenedor al 5173 de la máquina host
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
